language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t makmakkerti/complex-fib-app -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true makmakkerti/complex-fib-app npm test

after_success:
  - docker build -t makmakkerti/fib-client ./client
  - docker build -t makmakkerti/fib-nginx ./nginx
  - docker build -t makmakkerti/fib-server ./server
  - docker build -t makmakkerti/fib-worker ./worker
  # Login to the docker via CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to the docker hub
  - docker push makmakkerti/fib-client
  - docker push makmakkerti/fib-nginx 
  - docker push makmakkerti/fib-server
  - docker push makmakkerti/fib-worker
